# Generated by Django 4.0.4 on 2022-05-04 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trackers', '0003_alter_tracker_options_tracker_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='tracker',
            name='active',
            field=models.BooleanField(default=True, verbose_name='активен'),
        ),
    ]
