# Generated by Django 4.0.4 on 2022-05-04 22:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trackers', '0004_tracker_active'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tracker',
            options={'ordering': ['-active', 'name'], 'verbose_name': 'трекер', 'verbose_name_plural': 'трекеры'},
        ),
    ]
